[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "contracts/=src/contracts/",
    "priceConverter/=src/lib/priceConverter/",
    "script/=script/",
    "mocks/=src/contracts/mocks/"
]